// Generated by CoffeeScript 1.6.3
(function() {
  var test, vimhl;

  vimhl = require('./vimhl').vimHighlight;

  test = "filetype off            \" haha\nif isdirectory($HOME . \"/.vim/bundle/accelerated-jk\")        \" a variable not assigned\n    nmap j <Plug>(accelerated_jk_gj)\n    nmap k <Plug>(accelerated_jk_gk)\nendif\nlet g:accelerated_jk_acceleration_limit = 500\nlet g:accelerated_jk_acceleration_table = [10, 20, 30, 35, 40, 45, 50]\n\nnnoremap n nzzzv\nnnoremap N Nzzzv\nnnoremap <c-l> $\nnnoremap <c-h> 0\nimap <c-h> <Left>\nimap <c-j> <Down>\nimap <c-k> <Up>\nimap <c-l> <Right>\nimap <c-e> <End>\nimap <c-d> <Home>\ninoremap <c-b> <S-Left>\ninoremap <a-f> <S-Right>\ninoremap <a-b> <S-Left>\ncmap <c-j> <Down>\ncmap <c-k> <Up>\ncmap <c-h> <Left>\ncmap <c-l> <Right>\ncmap <a-f> <S-Right>\ncmap <c-b> <S-Left>\ncmap <a-b> <S-Left>\ncmap <c-e> <End>\ncmap <c-d> <Home>\n\" undoable C-U, C-W\ninoremap <c-u> <c-g>u<c-u>\ninoremap <c-w> <c-g>u<c-w>\n\"vnoremap << <gv<gv\n\"vnoremap >> >gv>gv\n\" Save Cursor Position:\nau BufReadPost *\n           \ if line(\"'\"\") > 0 && line(\"'\"\") <= line(\"$\") |\n           \   exe \"normal g`\"\" |\n           \ endif\n\" Hint On Moving Cursor:\nfunc HintCursorLine(opr)\n    if a:opr == 0            \" clear cursorline\n        set nocursorline\n        if exists(\"&cc\") | set cc= | endif\n        return\n    endif\n\n    if ! exists('g:last_line') | let g:last_line = -1 | end\n    if ! exists('g:last_pos')  | let g:last_pos  = -1 | end\n    if ! exists('g:last_win')  | let g:last_win  = -1 | end\n    let cur_pos  = winline()\n    let cur_line = line(\".\")\n    let diff = max([ abs(g:last_line - cur_line), abs(g:last_pos - cur_pos) ])\n    if g:last_win != winnr() || diff > 3\n        set cursorline\n    endif\n    let g:last_pos  = cur_pos\n    let g:last_line = cur_line\n    let g:last_win  = winnr()\nendfunc";

  console.log(vimhl(test, 'vim'));

}).call(this);
