// Generated by CoffeeScript 1.8.0
(function() {
  var cheerio, execSync, formatFilter, fs, temp, vimHighlight;

  execSync = require('execSync').exec;

  fs = require('fs');

  temp = require('temp');

  cheerio = require('cheerio');

  formatFilter = function(data) {
    data = data.trim();
    data = data.replace(/\n/, '');
    data = data.replace(/<br>/gi, '');
    data = data.replace(/0000c0/gi, '2277cc');
    data = data.replace(/af5f00/gi, 'd5e617');
    data = data.replace(/008080/gi, '0edbcb');
    data = data.replace(/008000/gi, '00c000');
    data = data.replace(/804000/gi, 'd5e617');
    return data;
  };

  vimHighlight = function(data, ft, useLineN) {
    var $, htmlPath, info, lineOpt, opt, result, ret;
    if (useLineN) {
      lineOpt = ' +"let g:html_number_lines=1" ';
    } else {
      lineOpt = ' +"let g:html_number_lines=0" ';
    }
    info = temp.openSync({
      suffix: '.' + ft
    });
    fs.writeSync(info.fd, data);
    fs.closeSync(info.fd);
    opt = ' +"let g:html_no_progress=1" +"let g:html_ignore_folding=1" +"let g:html_use_css=0" +"let g:html_pre_wrap=0" ' + lineOpt;
    execSync('vim -X -E -i NONE -f ' + opt + ' +"TOhtml" -cwqa ' + info.path + ' > /dev/null');
    htmlPath = info.path + '.html';
    result = fs.readFileSync(htmlPath);
    result = String(result);
    fs.unlink(htmlPath, function(err) {});
    fs.unlink(info.path, function(err) {});
    $ = cheerio.load(result);
    ret = $('body');
    ret = formatFilter(ret.html());
    return ret;
  };

  exports.vimHighlight = vimHighlight;

}).call(this);
